version: "2.4"
services:
  database:
    container_name: db_api
    image: ipekustynboyaci/trainingdbapi:0.0.1
    ports:
      - 5005:5005
    networks:
      - mynetwork
  datappapi:
    container_name: datapp_api
    image: ipekustynboyaci/datappapidbapi:0.0.1
    environment:
      - TRAININGDB_API='http://db_api:5005/training-db/housing'
    ports:
      - 5006:5006
    networks:
      - mynetwork
    depends_on:
      - database
  trainingapi:
    container_name: training
    image: ipekustunboyaci/trainingapi:0.0.1
    environment:
      - DB_API='http://datapp_api:5006/db_preprocessing/housing'
    ports:
      - 5000:5000
    networks:
      - mynetwork
    depends_on:
      - datappapi

networks:
  mynetwork: {}