version: '3.8'

volumes:
  spark-data:
    driver_opts:
      type: none
      device: /home/i_ustunboyacioglu/data
      o: bind
  notebooks:
    driver_opts:
      type: none
      device: /home/i_ustunboyacioglu/notebooks
      o: bind
  spark-checkpoint:
    driver_opts:
      type: none
      device: /home/i_ustunboyacioglu/checkpoint
      o: bind
services:
  spark-driver-app:
    build: jupyter-all-spark-notebook-gcp    # jupyter/all-spark-notebook with spark configurations for bigquery and gcs
    #    image: jupyter/all-spark-notebook:spark-3.1.1
    container_name: spark-driver-app
    user: root
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - notebooks:/home/jovyan/notebooks  # jovyan is the default user of the image all-spark-notebook:spark-3.1.2. Do not change this
      - spark-data:/home/jovyan/data
      - spark-checkpoint:/home/jovyan/checkpoint
  spark-master:
    build: ./spark-bitnami-python3.9
    container_name: spark-master
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_DAEMON_MEMORY=2G
      - SPARK_MASTER_OPTS="-Dspark.deploy.defaultCores=1"
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - spark-data:/home/jovyan/data
      - spark-checkpoint:/home/jovyan/checkpoint
  spark-worker-1:
    build: ./spark-bitnami-python3.9
    container_name: spark-worker-1
    user: root
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8081"
    volumes:
      - spark-data:/home/jovyan/data
      - spark-checkpoint:/home/jovyan/checkpoint
  spark-worker-2:
    build: ./spark-bitnami-python3.9
    container_name: spark-worker-2
    user: root
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8082:8081"
    volumes:
      - spark-data:/home/jovyan/data
      - spark-checkpoint:/home/jovyan/checkpoint
  